coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "tests/**/*"
  - "setup.py"
  - "conftest.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  after_n_builds: 1 