coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "tests/**/*"
  - "setup.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 