# Script_python/config.yaml
# Pipeline Configuration
pipeline:
  version: "1.1.2"
  state_code: 6  # California

# Data Paths
paths:
  # State-level data
  household_data: "data/hca_2022.csv"  # California households
  person_data: "data/pca_2022.csv"     # California persons
  
  # Intermediate outputs (state-level)
  state_eligible_households: "output/ca_eligible_households.csv"
  state_eligible_persons: "output/ca_eligible_persons.csv"
  
  # Region-specific outputs
  eligible_households: "output/eligible_calworks_sf_households.csv"
  eligible_persons: "output/eligible_calworks_sf_persons.csv"
  
  # Analysis outputs
  output_dir: "output"
  plots_dir: "docs/images"

# Region Selection
regions:
  default: "san_francisco"  # Default region to analyze
  definitions:
    san_francisco:
      name: "San Francisco"
      puma_codes: [7507, 7508, 7509, 7510, 7511, 7512, 7513, 7514]
      description: "San Francisco County PUMAs"
    # Add other regions as needed:
    # alameda:
    #   name: "Alameda County"
    #   puma_codes: [...]

# Income Thresholds
income:
  earned_income_disregard: 450
  income_columns:
    earned: ["WAGP", "SEMP"]  # Employment income
    unearned: ["RETP", "INTP", "PAP", "SSP"]  # Other income sources

# MBSAC Thresholds (Monthly)
mbsac_thresholds:
  1: 899
  2: 1476
  3: 1829
  4: 2170
  5: 2476
  6: 2785
  7: 3061
  8: 3331
  9: 3614
  10: 3922
  additional_person: 308  # Amount to add for each person over 10

